import React from "react";
// import "@assets/plugins/bootstrap/css/bootstrap.min.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "@assets/plugins/html5-editor/bootstrap-wysihtml5.css";
import "@assets/plugins/c3-master/c3.min.css";
import "@assets/css/style.css";
import "@assets/css/colors/default.css";

import Script from "next/script";
import BreadCrumb from "@components/BreadCrumb";
import RightMenu from "@components/RightMenu";
import LeftMenu from "@components/LeftMenu";
import Footer from "@components/Footer";
import Navbar from "@components/Navbar";
import SSRProvider from "react-bootstrap/SSRProvider";

export const metadata = {
  title: "Rasen - Seller Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Script src="/assets/plugins/jquery/jquery.min.js" />
      <Script src="/assets/plugins/popper/popper.min.js" />
      <Script src="/assets/plugins/bootstrap/js/bootstrap.min.js" />
      <Script src="/assets/js/jquery.slimscroll.js" />
      <Script src="/assets/js/waves.js" />
      <Script src="/assets/js/sidebarmenu.js" />
      <Script src="/assets/plugins/sticky-kit-master/dist/sticky-kit.min.js" />
      <Script src="/assets/plugins/sparkline/jquery.sparkline.min.js" />
      <Script src="/assets/js/custom.min.js" />
      <Script src="/assets/plugins/d3/d3.min.js" />
      <Script src="/assets/plugins/c3-master/c3.min.js" />
      <Script src="/assets/js/dashboard1.js" />
      <Script src="/assets/plugins/styleswitcher/jQuery.style.switcher.js" />
      <SSRProvider>
        <body className="fix-header fix-sidebar card-no-border">
          <div className="preloader">
            <svg className="circular" viewBox="25 25 50 50">
              <circle
                className="path"
                cx="50"
                cy="50"
                r="20"
                fill="none"
                strokeWidth="2"
                strokeMiterlimit="10"
              />
            </svg>
          </div>
          <div id="main-wrapper">
            <Navbar />
            <LeftMenu />
            <div className="page-wrapper">
              <div className="container-fluid">
                <BreadCrumb />
                {children}
                <RightMenu />
              </div>
              <Footer />
            </div>
          </div>
        </body>
      </SSRProvider>
    </html>
  );
}
